# Custom aliases

# Terminal
alias c='clear'
alias chzsh='chsh -s $(which zsh)'

# Navigation
alias h='cd ~'
alias b='cd ..'
alias p='cd -'

# Installation
alias get='sudo apt-get install -y'
alias repo='sudo add-apt-repository'
alias rem='sudo apt-get remove -y'
alias up='sudo apt-get update'

# Power
alias off='shutdown -h now'
alias re='reboot'

# Favorite folders
alias dev='cd ~/local-dev'
alias dot='cd ~/dotfiles'

# Projects
alias omg='cd ~/local-dev/omega'
alias omc='cd ~/local-dev/omega/monorepo'

# Edit config files
alias cfv='vim ~/.vimrc'
alias cft='vim ~/.tmux.conf'
alias cfb='vim ~/.bashrc'
alias cfa='vim ~/.bash_aliases'
alias cfg='vim ~/.gitconfig'
alias cfm='vim ~/.Xmodmap'
alias cfx='vim ~/.xsessionrc'
alias cfh='sudo vim /etc/hosts'

# Git commands
alias g='git'
alias gst='git status'
alias ga='git add .'
alias gac='git add . && git commit -m'
alias gco='git checkout'
alias gcob='git checkout --branch'

# Tmux commands
alias tms='tmux new -s'
alias tmw='tmux new-window -n'
alias tma='tmux attach -t'
alias tmx='tmux switch -t'
alias tmr='tmux rename-session'
alias tml='tmux ls'

# Python commands
# alias venv2='virtualenv -p python2 env'
# alias venv3='virtualenv -p python3 env'
# alias act='source env/bin/activate'
# alias deact='deactivate'

# Vagrant commands
# alias hsup='hs up'
# alias hssh='hs ssh'
# alias hstop='hs halt'

