# Setup pre tools: tools that should be loaded at top of .zshrc
[ -f ~/.shell/zsh-pre-tools.sh ] && . ~/.shell/zsh-pre-tools.sh

#""""""""""""""""""""""""""""""
#"          History           "
#""""""""""""""""""""""""""""""

HISTFILE="$HOME/.zsh_history"
HISTSIZE=50000
SAVEHIST=50000

setopt EXTENDED_HISTORY        # record timestamp of each command
setopt INC_APPEND_HISTORY      # write as you go, not only on exit
setopt SHARE_HISTORY           # share history across running sessions
setopt HIST_EXPIRE_DUPS_FIRST  # trim duplicates first when trimming
setopt HIST_IGNORE_DUPS        # don't record a command repeated back to back
setopt HIST_IGNORE_SPACE       # don't record commands prefixed with a space
setopt HIST_VERIFY             # expand !! into the buffer instead of running it

#""""""""""""""""""""""""""""""
#"        Shell options       "
#""""""""""""""""""""""""""""""

setopt AUTO_CD                 # bare directory name means cd
setopt AUTO_PUSHD              # every cd pushes onto the dir stack
setopt PUSHD_IGNORE_DUPS
setopt PUSHD_MINUS             # make `cd -1` mean one back, not one forward
setopt INTERACTIVE_COMMENTS    # allow # comments in the interactive shell

#""""""""""""""""""""""""""""""
#"           Paths            "
#""""""""""""""""""""""""""""""

# Keep $path free of duplicates, however many times something appends to it
typeset -U path PATH

# Add local binaries to path
export PATH="$HOME/.local/bin:/usr/local/bin:$PATH"

#""""""""""""""""""""""""""""""
#"        Completion          "
#""""""""""""""""""""""""""""""

# Homebrew's extra completion functions (git, brew, ...)
if [ -d /opt/homebrew/share/zsh/site-functions ]; then
  fpath=(/opt/homebrew/share/zsh/site-functions $fpath)
fi

# Rebuild the completion dump at most once a day; otherwise load it as-is
_zcompdump="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/zcompdump"
[ -d "${_zcompdump:h}" ] || mkdir -p "${_zcompdump:h}"

autoload -Uz compinit
if [[ -n ${_zcompdump}(#qN.mh-24) ]]; then
  compinit -C -d "$_zcompdump"   # dump is fresh, skip the security check
else
  compinit -d "$_zcompdump"
fi
unset _zcompdump

# Enable completion for bash-style completion scripts
autoload -U bashcompinit
bashcompinit

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' special-dirs true
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "${XDG_CACHE_HOME:-$HOME/.cache}/zsh/zcompcache"

#""""""""""""""""""""""""""""""
#"        Keybindings         "
#""""""""""""""""""""""""""""""

# Enable vi mode
bindkey -v

#""""""""""""""""""""""""""""""
#"     Aliases and tools      "
#""""""""""""""""""""""""""""""

# Load local config
[ -f ~/.local/zshrc.local ] && . ~/.local/zshrc.local

# Load aliases
[ -f ~/.shell/aliases.sh ] && . ~/.shell/aliases.sh

# Setup tools -- prompt and plugins live here, must stay the last line
[ -f ~/.shell/tools.sh ] && . ~/.shell/tools.sh
