# Setup pre tools: tools that should be loaded at top of .zshrc
[ -f ~/.shell/zsh-pre-tools.sh ] && . ~/.shell/zsh-pre-tools.sh

# Set default theme
ZSH_THEME="agnoster"

# Load local config
[ -f ~/.local/zshrc.local ] && . ~/.local/zshrc.local

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
source $ZSH/oh-my-zsh.sh

# Add local binaries to path
export PATH="$HOME/.local/bin:usr/local/bin:$PATH"

# Enable vi mode
bindkey -v

# Enable reverse search
bindkey "^R" history-incremental-search-backward

# Enable shell completion
autoload -U bashcompinit
bashcompinit

# Load aliases
[ -f ~/.shell/aliases.sh ] && . ~/.shell/aliases.sh

# Setup tools
[ -f ~/.shell/tools.sh ] && . ~/.shell/tools.sh

