# Custom aliases

# Terminal
alias c='clear'

# Navigation
alias h='cd ~'
alias b='cd ..'
alias p='cd -'

# Installation
alias get='sudo apt-get install -y'
alias repo='sudo add-apt-repository'
alias rem='sudo apt-get remove -y'
alias up='sudo apt-get update'

# Power
alias off='shutdown -h now'
alias re='reboot'

# Favorite folders
alias dev='cd ~/local-dev'
alias dot='cd ~/dotfiles'

# Edit config files
alias cfv='vim ~/.vimrc'
alias cfb='vim ~/.bashrc'
alias cfa='vim ~/.bash_aliases'
alias cfg='vim ~/.gitconfig'
alias cfm='vim ~/.Xmodmap'
alias cfx='vim ~/.xsessionrc'
alias cfhs='vim ~/homestead/Homestead.yaml'
alias cfh='sudo vim /etc/hosts'

# Vagrant commands
alias hsup='hs up'
alias hssh='hs ssh'
alias hstop='hs halt'

